# Generated by Django 2.1.2 on 2018-11-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0003_auto_20181128_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
