# Generated by Django 2.1.2 on 2018-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0004_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created_on', models.DateField(auto_now=True)),
                ('post_image_1', models.ImageField(upload_to='post_images')),
                ('post_image_2', models.ImageField(upload_to='post_images')),
                ('post_image_3', models.ImageField(upload_to='post_images')),
                ('post_image_4', models.ImageField(upload_to='post_images')),
                ('post_image_5', models.ImageField(upload_to='post_images')),
                ('post_image_6', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
