# Generated by Django 2.1.2 on 2018-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0006_teamprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
