# Generated by Django 2.1.2 on 2018-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0008_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='client_logo')),
                ('client_website', models.URLField(blank=True)),
            ],
        ),
    ]
