# Generated by Django 2.1.3 on 2018-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0009_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='post_images')),
                ('image_2', models.ImageField(upload_to='post_images')),
                ('image_3', models.ImageField(upload_to='post_images')),
                ('image_4', models.ImageField(upload_to='post_images')),
                ('image_5', models.ImageField(upload_to='post_images')),
                ('image_6', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
