# Generated by Django 2.1.3 on 2018-11-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0012_artist_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
