# Generated by Django 2.1.3 on 2018-11-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0014_artist_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistGallery',
            fields=[
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kibz.Artist')),
                ('image_1', models.ImageField(upload_to='artist_images')),
                ('image_2', models.ImageField(upload_to='artist_images')),
                ('image_3', models.ImageField(upload_to='artist_images')),
                ('image_4', models.ImageField(upload_to='artist_images')),
                ('image_5', models.ImageField(upload_to='artist_images')),
            ],
        ),
    ]
