# Generated by Django 2.1.3 on 2018-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0017_auto_20181129_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgallery',
            name='owner',
            field=models.CharField(blank=True, default='artist', max_length=100, null=True),
        ),
    ]
