# Generated by Django 2.1.3 on 2018-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0018_auto_20181129_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistgallery',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_1',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='artist_images'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_2',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='artist_images'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_3',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='artist_images'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_4',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='artist_images'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_5',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='artist_images'),
        ),
        migrations.DeleteModel(
            name='ArtistGallery',
        ),
    ]
