# Generated by Django 2.1.3 on 2018-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibz', '0020_auto_20181129_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_1',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_2',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_3',
            field=models.URLField(max_length=500),
        ),
    ]
